export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAIL = 'USER_LOGIN_FAIL'
export const USER_LOGOUT = 'USER_LOGOUT'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL'
export const USER_REGISTER_RESET = 'USER_REGISTER_RESET'

export const USER_RECOVERY_EMAIL_SUCCESS = 'USER_RECOVERY_EMAIL_SUCCESS'
export const USER_RECOVERY_EMAIL_REQUEST = 'USER_RECOVERY_EMAIL_REQUEST'
export const USER_RECOVERY_EMAIL_FAIL = 'USER_RECOVERY_EMAIL_FAIL'
export const USER_RECOVERY_EMAIL_RESET = 'USER_RECOVERY_EMAIL_RESET'

export const USER_PASSWORD_RESET_REQUEST = 'USER_PASSWORD_RESET_REQUEST'
export const USER_PASSWORD_RESET_SUCCESS = 'USER_PASSWORD_RESET_SUCCESS'
export const USER_PASSWORD_RESET_FAIL = 'USER_PASSWORD_RESET_FAIL'
export const USER_PASSWORD_RESET_RESET = 'USER_PASSWORD_RESET_RESET'
